### PR TITLE
fix: reject rotated orthorhombic cell matrices

### LINKED ISSUE #384: Deal with vector permutation in the cell matrix
Chemfiles' latest addition allows constructing cells from arbitrary matrices. This makes life hard for this PR (diagonal for non--infinite cells might be all zeros) and might also have some issues in itself (e.g. `UnitCell({ 0, 0, 1, /**/ 1, 0, 0, /**/ 0, 1, 0 })` is erroneously(?) triclinic).

_Originally posted by @ezavod in https://github.com/chemfiles/chemfiles/issues/381#issuecomment-738287888_

### PR DESCRIPTION
**Pull request by ezavod**
Fixes #384 by rejecting unit cells that are not diagonal and orthorhombic. This means orthorhombic UnitCells can be constructed from diagonal matrices only.

### CODE REVIEW

File: src/UnitCell.cpp [hunk 1]
```diff
@@ -123,6 +159,12 @@ UnitCell::UnitCell(Matrix3D matrix): matrix_(std::move(matrix)), matrix_inv_(Mat
         throw error("invalid unit cell matrix with negative determinant");
     }
 
+    auto lengths = calc_lengths_from_cell_matrix(matrix_);
+    auto angles = calc_angles_from_cell_matrix(matrix_);
+    if (!is_diagonal(matrix_) && is_orthorhombic(lengths, angles)) {
+        throw error("rotated ORTHORHOMBIC cells are not supported");
```
Comment (Luthaf) [inline src/UnitCell.cpp:165]:
```suggestion
        throw error("orthorhombic cell must have their a vector along x axis, b vector along y axis and c vector along z axis");
```

**Review by Luthaf — APPROVED** [review]
Looks good. I'm trying to think of a similar issue with triclinic matrix, but I can not find one on the top of my head.

**Comment by ezavod** [comment]
> I'm trying to think of a similar issue with triclinic matrix, but I can not find one on the top of my head.

The main issue is that we treat orthorhombic cells specially. In case we want arbitrary rotated orthorhombic cells we can simply use `calc_*_from_cell_matrix` in `lengths()` and `angles()`. This would mean we treat triclinic and orthorhombic cells the same except the initial shape assignment. But that could be added later when a use-case arises.

**Review by Luthaf — APPROVED** [review]
