### PR TITLE
Respecting PDB standard for atom with more than 4 connections

### LINKED ISSUE #80: PDB format with more than 4 bonds per atom
If one atom has more than 4 bonds, chemfiles throws this error:
`PDB 'CONNECT' record can not handle more than 4 bonds, got 6 around atom 143.`

However, it should start a new CONECT line with the same ID number

### PR DESCRIPTION
**Pull request by lscalfi**
Fix #80

### CODE REVIEW

File: src/formats/PDB.cpp [hunk 1]
```diff
@@ -355,21 +355,19 @@ void PDBFormat::write(const Frame& frame) {
...
+        auto lines = std::ceil(connections/4.0);
         if (connections == 0) {
             continue;
-        } else if (connections > 4) {
-            warning(
-                "PDB 'CONNECT' record can not handle more than 4 bonds, got {} around atom {}.",
-                connections, i
-            );
-        }
+        };
```
Comment (Luthaf) [inline src/formats/PDB.cpp]: No need for semicolon here =)

**Comment by Luthaf** [comment]
Thank for the PR! This still miss a test 😉

**Comment by Luthaf** [comment]
Thanks!
